package com.github.aeddddd.ae2enhanced.structure;

import com.github.aeddddd.ae2enhanced.AE2Enhanced;
import com.github.aeddddd.ae2enhanced.ModBlocks;
import com.github.aeddddd.ae2enhanced.config.AE2EnhancedConfig;
import net.minecraft.block.Block;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

import java.util.*;

/**
 * �����������Ķ෽��ṹ��������֤��
 * ����ԭ��Ϊ������λ�� (0,0,0)����Ӧ JSON �е� (0,0,6)��
 */
public class SupercausalStructure {

    public static final BlockPos CONTROLLER_REL = new BlockPos(0, 0, 0);
    public static final BlockPos ME_INTERFACE_REL = new BlockPos(0, 0, -6);

    public static final Set<BlockPos> TENSOR_CASING_SET;
    public static final Set<BlockPos> CAUSAL_ANCHOR_SET;
    public static final Set<BlockPos> SPINOR_CASING_SET;
    public static final Set<BlockPos> ALL_STRUCTURE_SET;

    static {
        Set<BlockPos> tensor = new HashSet<>();
        tensor.add(new BlockPos(-12, 0, 2));
        tensor.add(new BlockPos(-12, 0, 3));
        tensor.add(new BlockPos(-12, 0, 4));
        tensor.add(new BlockPos(-12, 0, 5));
        tensor.add(new BlockPos(-12, 0, 6));
        tensor.add(new BlockPos(-12, 0, 7));
        tensor.add(new BlockPos(-12, 0, 8));
        tensor.add(new BlockPos(-12, 0, 9));
        tensor.add(new BlockPos(-12, 0, 10));
        tensor.add(new BlockPos(-11, 0, 0));
        tensor.add(new BlockPos(-11, 0, 1));
        tensor.add(new BlockPos(-11, 0, 6));
        tensor.add(new BlockPos(-11, 0, 7));
        tensor.add(new BlockPos(-10, 0, -1));
        tensor.add(new BlockPos(-10, 0, 4));
        tensor.add(new BlockPos(-10, 0, 5));
        tensor.add(new BlockPos(-9, 0, -2));
        tensor.add(new BlockPos(-9, 0, 3));
        tensor.add(new BlockPos(-9, 0, 4));
        tensor.add(new BlockPos(-8, 0, -3));
        tensor.add(new BlockPos(-8, 0, 2));
        tensor.add(new BlockPos(-8, 0, 3));
        tensor.add(new BlockPos(-7, 0, -4));
        tensor.add(new BlockPos(-7, 0, 2));
        tensor.add(new BlockPos(-6, 0, -5));
        tensor.add(new BlockPos(-6, 0, 1));
        tensor.add(new BlockPos(-5, 0, -5));
        tensor.add(new BlockPos(-5, 0, 1));
        tensor.add(new BlockPos(-4, 0, -6));
        tensor.add(new BlockPos(-4, 0, 0));
        tensor.add(new BlockPos(-3, 0, -6));
        tensor.add(new BlockPos(-3, 0, 0));
        tensor.add(new BlockPos(-2, 0, -6));
        tensor.add(new BlockPos(-2, 0, 0));
        tensor.add(new BlockPos(-1, 0, -6));
        tensor.add(new BlockPos(-1, 0, 0));
        tensor.add(new BlockPos(0, -12, 2));
        tensor.add(new BlockPos(0, -12, 3));
        tensor.add(new BlockPos(0, -12, 4));
        tensor.add(new BlockPos(0, -12, 5));
        tensor.add(new BlockPos(0, -12, 6));
        tensor.add(new BlockPos(0, -12, 7));
        tensor.add(new BlockPos(0, -12, 8));
        tensor.add(new BlockPos(0, -12, 9));
        tensor.add(new BlockPos(0, -12, 10));
        tensor.add(new BlockPos(0, -11, 0));
        tensor.add(new BlockPos(0, -11, 1));
        tensor.add(new BlockPos(0, -11, 6));
        tensor.add(new BlockPos(0, -11, 7));
        tensor.add(new BlockPos(0, -10, -1));
        tensor.add(new BlockPos(0, -10, 4));
        tensor.add(new BlockPos(0, -10, 5));
        tensor.add(new BlockPos(0, -9, -2));
        tensor.add(new BlockPos(0, -9, 3));
        tensor.add(new BlockPos(0, -9, 4));
        tensor.add(new BlockPos(0, -8, -3));
        tensor.add(new BlockPos(0, -8, 2));
        tensor.add(new BlockPos(0, -8, 3));
        tensor.add(new BlockPos(0, -7, -4));
        tensor.add(new BlockPos(0, -7, 2));
        tensor.add(new BlockPos(0, -6, -5));
        tensor.add(new BlockPos(0, -6, 1));
        tensor.add(new BlockPos(0, -5, -5));
        tensor.add(new BlockPos(0, -5, 1));
        tensor.add(new BlockPos(0, -4, -6));
        tensor.add(new BlockPos(0, -4, 0));
        tensor.add(new BlockPos(0, -3, -6));
        tensor.add(new BlockPos(0, -3, 0));
        tensor.add(new BlockPos(0, -2, -6));
        tensor.add(new BlockPos(0, -2, 0));
        tensor.add(new BlockPos(0, -1, -6));
        tensor.add(new BlockPos(0, -1, 0));
        tensor.add(new BlockPos(0, 0, 0));
        tensor.add(new BlockPos(0, 1, -6));
        tensor.add(new BlockPos(0, 1, 0));
        tensor.add(new BlockPos(0, 2, -6));
        tensor.add(new BlockPos(0, 2, 0));
        tensor.add(new BlockPos(0, 3, -6));
        tensor.add(new BlockPos(0, 3, 0));
        tensor.add(new BlockPos(0, 4, -6));
        tensor.add(new BlockPos(0, 4, 0));
        tensor.add(new BlockPos(0, 5, -5));
        tensor.add(new BlockPos(0, 5, 1));
        tensor.add(new BlockPos(0, 6, -5));
        tensor.add(new BlockPos(0, 6, 1));
        tensor.add(new BlockPos(0, 7, -4));
        tensor.add(new BlockPos(0, 7, 2));
        tensor.add(new BlockPos(0, 8, -3));
        tensor.add(new BlockPos(0, 8, 2));
        tensor.add(new BlockPos(0, 8, 3));
        tensor.add(new BlockPos(0, 9, -2));
        tensor.add(new BlockPos(0, 9, 3));
        tensor.add(new BlockPos(0, 9, 4));
        tensor.add(new BlockPos(0, 10, -1));
        tensor.add(new BlockPos(0, 10, 4));
        tensor.add(new BlockPos(0, 10, 5));
        tensor.add(new BlockPos(0, 11, 0));
        tensor.add(new BlockPos(0, 11, 1));
        tensor.add(new BlockPos(0, 11, 6));
        tensor.add(new BlockPos(0, 11, 7));
        tensor.add(new BlockPos(0, 12, 2));
        tensor.add(new BlockPos(0, 12, 3));
        tensor.add(new BlockPos(0, 12, 4));
        tensor.add(new BlockPos(0, 12, 5));
        tensor.add(new BlockPos(0, 12, 6));
        tensor.add(new BlockPos(0, 12, 7));
        tensor.add(new BlockPos(0, 12, 8));
        tensor.add(new BlockPos(0, 12, 9));
        tensor.add(new BlockPos(0, 12, 10));
        tensor.add(new BlockPos(1, 0, -6));
        tensor.add(new BlockPos(1, 0, 0));
        tensor.add(new BlockPos(2, 0, -6));
        tensor.add(new BlockPos(2, 0, 0));
        tensor.add(new BlockPos(3, 0, -6));
        tensor.add(new BlockPos(3, 0, 0));
        tensor.add(new BlockPos(4, 0, -6));
        tensor.add(new BlockPos(4, 0, 0));
        tensor.add(new BlockPos(5, 0, -5));
        tensor.add(new BlockPos(5, 0, 1));
        tensor.add(new BlockPos(6, 0, -5));
        tensor.add(new BlockPos(6, 0, 1));
        tensor.add(new BlockPos(7, 0, -4));
        tensor.add(new BlockPos(7, 0, 2));
        tensor.add(new BlockPos(8, 0, -3));
        tensor.add(new BlockPos(8, 0, 2));
        tensor.add(new BlockPos(8, 0, 3));
        tensor.add(new BlockPos(9, 0, -2));
        tensor.add(new BlockPos(9, 0, 3));
        tensor.add(new BlockPos(9, 0, 4));
        tensor.add(new BlockPos(10, 0, -1));
        tensor.add(new BlockPos(10, 0, 4));
        tensor.add(new BlockPos(10, 0, 5));
        tensor.add(new BlockPos(11, 0, 0));
        tensor.add(new BlockPos(11, 0, 1));
        tensor.add(new BlockPos(11, 0, 6));
        tensor.add(new BlockPos(11, 0, 7));
        tensor.add(new BlockPos(12, 0, 2));
        tensor.add(new BlockPos(12, 0, 3));
        tensor.add(new BlockPos(12, 0, 4));
        tensor.add(new BlockPos(12, 0, 5));
        tensor.add(new BlockPos(12, 0, 6));
        tensor.add(new BlockPos(12, 0, 7));
        tensor.add(new BlockPos(12, 0, 8));
        tensor.add(new BlockPos(12, 0, 9));
        tensor.add(new BlockPos(12, 0, 10));
        TENSOR_CASING_SET = Collections.unmodifiableSet(tensor);

        Set<BlockPos> causal = new HashSet<>();
        causal.add(new BlockPos(-11, 0, 2));
        causal.add(new BlockPos(-11, 0, 3));
        causal.add(new BlockPos(-11, 0, 4));
        causal.add(new BlockPos(-11, 0, 5));
        causal.add(new BlockPos(-10, 0, 0));
        causal.add(new BlockPos(-10, 0, 1));
        causal.add(new BlockPos(-10, 0, 2));
        causal.add(new BlockPos(-10, 0, 3));
        causal.add(new BlockPos(-9, 0, -1));
        causal.add(new BlockPos(-9, 0, 0));
        causal.add(new BlockPos(-9, 0, 1));
        causal.add(new BlockPos(-9, 0, 2));
        causal.add(new BlockPos(-8, -1, 0));
        causal.add(new BlockPos(-8, 0, -2));
        causal.add(new BlockPos(-8, 0, -1));
        causal.add(new BlockPos(-8, 0, 0));
        causal.add(new BlockPos(-8, 0, 1));
        causal.add(new BlockPos(-8, 1, 0));
        causal.add(new BlockPos(-7, -1, -1));
        causal.add(new BlockPos(-7, 0, -3));
        causal.add(new BlockPos(-7, 0, -2));
        causal.add(new BlockPos(-7, 0, -1));
        causal.add(new BlockPos(-7, 0, 0));
        causal.add(new BlockPos(-7, 0, 1));
        causal.add(new BlockPos(-7, 1, -1));
        causal.add(new BlockPos(-6, -1, -2));
        causal.add(new BlockPos(-6, -1, -1));
        causal.add(new BlockPos(-6, 0, -4));
        causal.add(new BlockPos(-6, 0, -3));
        causal.add(new BlockPos(-6, 0, -2));
        causal.add(new BlockPos(-6, 0, -1));
        causal.add(new BlockPos(-6, 0, 0));
        causal.add(new BlockPos(-6, 1, -2));
        causal.add(new BlockPos(-6, 1, -1));
        causal.add(new BlockPos(-5, -1, -3));
        causal.add(new BlockPos(-5, -1, -2));
        causal.add(new BlockPos(-5, 0, -4));
        causal.add(new BlockPos(-5, 0, -3));
        causal.add(new BlockPos(-5, 0, -2));
        causal.add(new BlockPos(-5, 0, -1));
        causal.add(new BlockPos(-5, 0, 0));
        causal.add(new BlockPos(-5, 1, -3));
        causal.add(new BlockPos(-5, 1, -2));
        causal.add(new BlockPos(-4, -1, -3));
        causal.add(new BlockPos(-4, -1, -2));
        causal.add(new BlockPos(-4, 0, -5));
        causal.add(new BlockPos(-4, 0, -4));
        causal.add(new BlockPos(-4, 0, -3));
        causal.add(new BlockPos(-4, 0, -2));
        causal.add(new BlockPos(-4, 0, -1));
        causal.add(new BlockPos(-4, 1, -3));
        causal.add(new BlockPos(-4, 1, -2));
        causal.add(new BlockPos(-3, -2, -3));
        causal.add(new BlockPos(-3, -1, -4));
        causal.add(new BlockPos(-3, -1, -3));
        causal.add(new BlockPos(-3, -1, -2));
        causal.add(new BlockPos(-3, 0, -5));
        causal.add(new BlockPos(-3, 0, -4));
        causal.add(new BlockPos(-3, 0, -3));
        causal.add(new BlockPos(-3, 0, -2));
        causal.add(new BlockPos(-3, 0, -1));
        causal.add(new BlockPos(-3, 1, -4));
        causal.add(new BlockPos(-3, 1, -3));
        causal.add(new BlockPos(-3, 1, -2));
        causal.add(new BlockPos(-3, 2, -3));
        causal.add(new BlockPos(-2, -3, -3));
        causal.add(new BlockPos(-2, -2, -3));
        causal.add(new BlockPos(-2, -1, -4));
        causal.add(new BlockPos(-2, -1, -3));
        causal.add(new BlockPos(-2, -1, -2));
        causal.add(new BlockPos(-2, 0, -5));
        causal.add(new BlockPos(-2, 0, -4));
        causal.add(new BlockPos(-2, 0, -3));
        causal.add(new BlockPos(-2, 0, -2));
        causal.add(new BlockPos(-2, 0, -1));
        causal.add(new BlockPos(-2, 1, -4));
        causal.add(new BlockPos(-2, 1, -3));
        causal.add(new BlockPos(-2, 1, -2));
        causal.add(new BlockPos(-2, 2, -3));
        causal.add(new BlockPos(-2, 3, -3));
        causal.add(new BlockPos(-1, -9, 0));
        causal.add(new BlockPos(-1, -8, 0));
        causal.add(new BlockPos(-1, -7, -1));
        causal.add(new BlockPos(-1, -6, -2));
        causal.add(new BlockPos(-1, -6, -1));
        causal.add(new BlockPos(-1, -5, -3));
        causal.add(new BlockPos(-1, -5, -2));
        causal.add(new BlockPos(-1, -4, -3));
        causal.add(new BlockPos(-1, -4, -2));
        causal.add(new BlockPos(-1, -3, -4));
        causal.add(new BlockPos(-1, -3, -3));
        causal.add(new BlockPos(-1, -3, -2));
        causal.add(new BlockPos(-1, -2, -4));
        causal.add(new BlockPos(-1, -2, -3));
        causal.add(new BlockPos(-1, -2, -2));
        causal.add(new BlockPos(-1, -1, -4));
        causal.add(new BlockPos(-1, -1, -3));
        causal.add(new BlockPos(-1, -1, -2));
        causal.add(new BlockPos(-1, 0, -5));
        causal.add(new BlockPos(-1, 0, -4));
        causal.add(new BlockPos(-1, 0, -3));
        causal.add(new BlockPos(-1, 0, -2));
        causal.add(new BlockPos(-1, 0, -1));
        causal.add(new BlockPos(-1, 1, -4));
        causal.add(new BlockPos(-1, 1, -3));
        causal.add(new BlockPos(-1, 1, -2));
        causal.add(new BlockPos(-1, 2, -4));
        causal.add(new BlockPos(-1, 2, -3));
        causal.add(new BlockPos(-1, 2, -2));
        causal.add(new BlockPos(-1, 3, -4));
        causal.add(new BlockPos(-1, 3, -3));
        causal.add(new BlockPos(-1, 3, -2));
        causal.add(new BlockPos(-1, 4, -3));
        causal.add(new BlockPos(-1, 4, -2));
        causal.add(new BlockPos(-1, 5, -3));
        causal.add(new BlockPos(-1, 5, -2));
        causal.add(new BlockPos(-1, 6, -2));
        causal.add(new BlockPos(-1, 6, -1));
        causal.add(new BlockPos(-1, 7, -1));
        causal.add(new BlockPos(-1, 8, 0));
        causal.add(new BlockPos(-1, 9, 0));
        causal.add(new BlockPos(0, -11, 2));
        causal.add(new BlockPos(0, -11, 3));
        causal.add(new BlockPos(0, -11, 4));
        causal.add(new BlockPos(0, -11, 5));
        causal.add(new BlockPos(0, -10, 0));
        causal.add(new BlockPos(0, -10, 1));
        causal.add(new BlockPos(0, -10, 2));
        causal.add(new BlockPos(0, -10, 3));
        causal.add(new BlockPos(0, -9, -1));
        causal.add(new BlockPos(0, -9, 0));
        causal.add(new BlockPos(0, -9, 1));
        causal.add(new BlockPos(0, -9, 2));
        causal.add(new BlockPos(0, -8, -2));
        causal.add(new BlockPos(0, -8, -1));
        causal.add(new BlockPos(0, -8, 0));
        causal.add(new BlockPos(0, -8, 1));
        causal.add(new BlockPos(0, -7, -3));
        causal.add(new BlockPos(0, -7, -2));
        causal.add(new BlockPos(0, -7, -1));
        causal.add(new BlockPos(0, -7, 0));
        causal.add(new BlockPos(0, -7, 1));
        causal.add(new BlockPos(0, -6, -4));
        causal.add(new BlockPos(0, -6, -3));
        causal.add(new BlockPos(0, -6, -2));
        causal.add(new BlockPos(0, -6, -1));
        causal.add(new BlockPos(0, -6, 0));
        causal.add(new BlockPos(0, -5, -4));
        causal.add(new BlockPos(0, -5, -3));
        causal.add(new BlockPos(0, -5, -2));
        causal.add(new BlockPos(0, -5, -1));
        causal.add(new BlockPos(0, -5, 0));
        causal.add(new BlockPos(0, -4, -5));
        causal.add(new BlockPos(0, -4, -4));
        causal.add(new BlockPos(0, -4, -3));
        causal.add(new BlockPos(0, -4, -2));
        causal.add(new BlockPos(0, -4, -1));
        causal.add(new BlockPos(0, -3, -5));
        causal.add(new BlockPos(0, -3, -4));
        causal.add(new BlockPos(0, -3, -3));
        causal.add(new BlockPos(0, -3, -2));
        causal.add(new BlockPos(0, -3, -1));
        causal.add(new BlockPos(0, -2, -5));
        causal.add(new BlockPos(0, -2, -4));
        causal.add(new BlockPos(0, -2, -3));
        causal.add(new BlockPos(0, -2, -2));
        causal.add(new BlockPos(0, -2, -1));
        causal.add(new BlockPos(0, -1, -5));
        causal.add(new BlockPos(0, -1, -4));
        causal.add(new BlockPos(0, -1, -3));
        causal.add(new BlockPos(0, -1, -2));
        causal.add(new BlockPos(0, -1, -1));
        causal.add(new BlockPos(0, 0, -5));
        causal.add(new BlockPos(0, 0, -4));
        causal.add(new BlockPos(0, 0, -3));
        causal.add(new BlockPos(0, 0, -2));
        causal.add(new BlockPos(0, 0, -1));
        causal.add(new BlockPos(0, 1, -5));
        causal.add(new BlockPos(0, 1, -4));
        causal.add(new BlockPos(0, 1, -3));
        causal.add(new BlockPos(0, 1, -2));
        causal.add(new BlockPos(0, 1, -1));
        causal.add(new BlockPos(0, 2, -5));
        causal.add(new BlockPos(0, 2, -4));
        causal.add(new BlockPos(0, 2, -3));
        causal.add(new BlockPos(0, 2, -2));
        causal.add(new BlockPos(0, 2, -1));
        causal.add(new BlockPos(0, 3, -5));
        causal.add(new BlockPos(0, 3, -4));
        causal.add(new BlockPos(0, 3, -3));
        causal.add(new BlockPos(0, 3, -2));
        causal.add(new BlockPos(0, 3, -1));
        causal.add(new BlockPos(0, 4, -5));
        causal.add(new BlockPos(0, 4, -4));
        causal.add(new BlockPos(0, 4, -3));
        causal.add(new BlockPos(0, 4, -2));
        causal.add(new BlockPos(0, 4, -1));
        causal.add(new BlockPos(0, 5, -4));
        causal.add(new BlockPos(0, 5, -3));
        causal.add(new BlockPos(0, 5, -2));
        causal.add(new BlockPos(0, 5, -1));
        causal.add(new BlockPos(0, 5, 0));
        causal.add(new BlockPos(0, 6, -4));
        causal.add(new BlockPos(0, 6, -3));
        causal.add(new BlockPos(0, 6, -2));
        causal.add(new BlockPos(0, 6, -1));
        causal.add(new BlockPos(0, 6, 0));
        causal.add(new BlockPos(0, 7, -3));
        causal.add(new BlockPos(0, 7, -2));
        causal.add(new BlockPos(0, 7, -1));
        causal.add(new BlockPos(0, 7, 0));
        causal.add(new BlockPos(0, 7, 1));
        causal.add(new BlockPos(0, 8, -2));
        causal.add(new BlockPos(0, 8, -1));
        causal.add(new BlockPos(0, 8, 0));
        causal.add(new BlockPos(0, 8, 1));
        causal.add(new BlockPos(0, 9, -1));
        causal.add(new BlockPos(0, 9, 0));
        causal.add(new BlockPos(0, 9, 1));
        causal.add(new BlockPos(0, 9, 2));
        causal.add(new BlockPos(0, 10, 0));
        causal.add(new BlockPos(0, 10, 1));
        causal.add(new BlockPos(0, 10, 2));
        causal.add(new BlockPos(0, 10, 3));
        causal.add(new BlockPos(0, 11, 2));
        causal.add(new BlockPos(0, 11, 3));
        causal.add(new BlockPos(0, 11, 4));
        causal.add(new BlockPos(0, 11, 5));
        causal.add(new BlockPos(1, -8, 0));
        causal.add(new BlockPos(1, -7, -1));
        causal.add(new BlockPos(1, -6, -2));
        causal.add(new BlockPos(1, -6, -1));
        causal.add(new BlockPos(1, -5, -3));
        causal.add(new BlockPos(1, -5, -2));
        causal.add(new BlockPos(1, -4, -3));
        causal.add(new BlockPos(1, -4, -2));
        causal.add(new BlockPos(1, -3, -4));
        causal.add(new BlockPos(1, -3, -3));
        causal.add(new BlockPos(1, -3, -2));
        causal.add(new BlockPos(1, -2, -4));
        causal.add(new BlockPos(1, -2, -3));
        causal.add(new BlockPos(1, -2, -2));
        causal.add(new BlockPos(1, -1, -4));
        causal.add(new BlockPos(1, -1, -3));
        causal.add(new BlockPos(1, -1, -2));
        causal.add(new BlockPos(1, 0, -5));
        causal.add(new BlockPos(1, 0, -4));
        causal.add(new BlockPos(1, 0, -3));
        causal.add(new BlockPos(1, 0, -2));
        causal.add(new BlockPos(1, 0, -1));
        causal.add(new BlockPos(1, 1, -4));
        causal.add(new BlockPos(1, 1, -3));
        causal.add(new BlockPos(1, 1, -2));
        causal.add(new BlockPos(1, 2, -4));
        causal.add(new BlockPos(1, 2, -3));
        causal.add(new BlockPos(1, 2, -2));
        causal.add(new BlockPos(1, 3, -4));
        causal.add(new BlockPos(1, 3, -3));
        causal.add(new BlockPos(1, 3, -2));
        causal.add(new BlockPos(1, 4, -3));
        causal.add(new BlockPos(1, 4, -2));
        causal.add(new BlockPos(1, 5, -3));
        causal.add(new BlockPos(1, 5, -2));
        causal.add(new BlockPos(1, 6, -2));
        causal.add(new BlockPos(1, 6, -1));
        causal.add(new BlockPos(1, 7, -1));
        causal.add(new BlockPos(1, 8, 0));
        causal.add(new BlockPos(2, -2, -3));
        causal.add(new BlockPos(2, -1, -4));
        causal.add(new BlockPos(2, -1, -3));
        causal.add(new BlockPos(2, -1, -2));
        causal.add(new BlockPos(2, 0, -5));
        causal.add(new BlockPos(2, 0, -4));
        causal.add(new BlockPos(2, 0, -3));
        causal.add(new BlockPos(2, 0, -2));
        causal.add(new BlockPos(2, 0, -1));
        causal.add(new BlockPos(2, 1, -4));
        causal.add(new BlockPos(2, 1, -3));
        causal.add(new BlockPos(2, 1, -2));
        causal.add(new BlockPos(2, 2, -3));
        causal.add(new BlockPos(3, -1, -4));
        causal.add(new BlockPos(3, -1, -3));
        causal.add(new BlockPos(3, -1, -2));
        causal.add(new BlockPos(3, 0, -5));
        causal.add(new BlockPos(3, 0, -4));
        causal.add(new BlockPos(3, 0, -3));
        causal.add(new BlockPos(3, 0, -2));
        causal.add(new BlockPos(3, 0, -1));
        causal.add(new BlockPos(3, 1, -4));
        causal.add(new BlockPos(3, 1, -3));
        causal.add(new BlockPos(3, 1, -2));
        causal.add(new BlockPos(4, -1, -3));
        causal.add(new BlockPos(4, -1, -2));
        causal.add(new BlockPos(4, 0, -5));
        causal.add(new BlockPos(4, 0, -4));
        causal.add(new BlockPos(4, 0, -3));
        causal.add(new BlockPos(4, 0, -2));
        causal.add(new BlockPos(4, 0, -1));
        causal.add(new BlockPos(4, 1, -3));
        causal.add(new BlockPos(4, 1, -2));
        causal.add(new BlockPos(5, -1, -3));
        causal.add(new BlockPos(5, -1, -2));
        causal.add(new BlockPos(5, 0, -4));
        causal.add(new BlockPos(5, 0, -3));
        causal.add(new BlockPos(5, 0, -2));
        causal.add(new BlockPos(5, 0, -1));
        causal.add(new BlockPos(5, 0, 0));
        causal.add(new BlockPos(5, 1, -3));
        causal.add(new BlockPos(5, 1, -2));
        causal.add(new BlockPos(6, -1, -2));
        causal.add(new BlockPos(6, -1, -1));
        causal.add(new BlockPos(6, 0, -4));
        causal.add(new BlockPos(6, 0, -3));
        causal.add(new BlockPos(6, 0, -2));
        causal.add(new BlockPos(6, 0, -1));
        causal.add(new BlockPos(6, 0, 0));
        causal.add(new BlockPos(6, 1, -2));
        causal.add(new BlockPos(6, 1, -1));
        causal.add(new BlockPos(7, -1, -1));
        causal.add(new BlockPos(7, 0, -3));
        causal.add(new BlockPos(7, 0, -2));
        causal.add(new BlockPos(7, 0, -1));
        causal.add(new BlockPos(7, 0, 0));
        causal.add(new BlockPos(7, 0, 1));
        causal.add(new BlockPos(7, 1, -1));
        causal.add(new BlockPos(8, -1, 0));
        causal.add(new BlockPos(8, 0, -2));
        causal.add(new BlockPos(8, 0, -1));
        causal.add(new BlockPos(8, 0, 0));
        causal.add(new BlockPos(8, 0, 1));
        causal.add(new BlockPos(8, 1, 0));
        causal.add(new BlockPos(9, 0, -1));
        causal.add(new BlockPos(9, 0, 0));
        causal.add(new BlockPos(9, 0, 1));
        causal.add(new BlockPos(9, 0, 2));
        causal.add(new BlockPos(10, 0, 0));
        causal.add(new BlockPos(10, 0, 1));
        causal.add(new BlockPos(10, 0, 2));
        causal.add(new BlockPos(10, 0, 3));
        causal.add(new BlockPos(11, 0, 2));
        causal.add(new BlockPos(11, 0, 3));
        causal.add(new BlockPos(11, 0, 4));
        causal.add(new BlockPos(11, 0, 5));
        CAUSAL_ANCHOR_SET = Collections.unmodifiableSet(causal);

        Set<BlockPos> spinor = new HashSet<>();
        spinor.add(new BlockPos(-11, -1, 2));
        spinor.add(new BlockPos(-11, -1, 3));
        spinor.add(new BlockPos(-11, -1, 4));
        spinor.add(new BlockPos(-11, -1, 5));
        spinor.add(new BlockPos(-11, 1, 2));
        spinor.add(new BlockPos(-11, 1, 3));
        spinor.add(new BlockPos(-11, 1, 4));
        spinor.add(new BlockPos(-11, 1, 5));
        spinor.add(new BlockPos(-10, -1, 0));
        spinor.add(new BlockPos(-10, -1, 1));
        spinor.add(new BlockPos(-10, -1, 2));
        spinor.add(new BlockPos(-10, -1, 3));
        spinor.add(new BlockPos(-10, 1, 0));
        spinor.add(new BlockPos(-10, 1, 1));
        spinor.add(new BlockPos(-10, 1, 2));
        spinor.add(new BlockPos(-10, 1, 3));
        spinor.add(new BlockPos(-9, -2, 0));
        spinor.add(new BlockPos(-9, -1, -1));
        spinor.add(new BlockPos(-9, -1, 0));
        spinor.add(new BlockPos(-9, -1, 1));
        spinor.add(new BlockPos(-9, -1, 2));
        spinor.add(new BlockPos(-9, 1, -1));
        spinor.add(new BlockPos(-9, 1, 0));
        spinor.add(new BlockPos(-9, 1, 1));
        spinor.add(new BlockPos(-9, 1, 2));
        spinor.add(new BlockPos(-9, 2, 0));
        spinor.add(new BlockPos(-8, -2, 0));
        spinor.add(new BlockPos(-8, -1, -2));
        spinor.add(new BlockPos(-8, -1, -1));
        spinor.add(new BlockPos(-8, -1, 1));
        spinor.add(new BlockPos(-8, 1, -2));
        spinor.add(new BlockPos(-8, 1, -1));
        spinor.add(new BlockPos(-8, 1, 1));
        spinor.add(new BlockPos(-8, 2, 0));
        spinor.add(new BlockPos(-7, -2, -1));
        spinor.add(new BlockPos(-7, -1, -3));
        spinor.add(new BlockPos(-7, -1, -2));
        spinor.add(new BlockPos(-7, -1, 0));
        spinor.add(new BlockPos(-7, -1, 1));
        spinor.add(new BlockPos(-7, 1, -3));
        spinor.add(new BlockPos(-7, 1, -2));
        spinor.add(new BlockPos(-7, 1, 0));
        spinor.add(new BlockPos(-7, 1, 1));
        spinor.add(new BlockPos(-7, 2, -1));
        spinor.add(new BlockPos(-6, -2, -2));
        spinor.add(new BlockPos(-6, -2, -1));
        spinor.add(new BlockPos(-6, -1, -4));
        spinor.add(new BlockPos(-6, -1, -3));
        spinor.add(new BlockPos(-6, -1, 0));
        spinor.add(new BlockPos(-6, 1, -4));
        spinor.add(new BlockPos(-6, 1, -3));
        spinor.add(new BlockPos(-6, 1, 0));
        spinor.add(new BlockPos(-6, 2, -2));
        spinor.add(new BlockPos(-6, 2, -1));
        spinor.add(new BlockPos(-5, -2, -3));
        spinor.add(new BlockPos(-5, -2, -2));
        spinor.add(new BlockPos(-5, -1, -4));
        spinor.add(new BlockPos(-5, -1, -1));
        spinor.add(new BlockPos(-5, -1, 0));
        spinor.add(new BlockPos(-5, 1, -4));
        spinor.add(new BlockPos(-5, 1, -1));
        spinor.add(new BlockPos(-5, 1, 0));
        spinor.add(new BlockPos(-5, 2, -3));
        spinor.add(new BlockPos(-5, 2, -2));
        spinor.add(new BlockPos(-4, -2, -3));
        spinor.add(new BlockPos(-4, -2, -2));
        spinor.add(new BlockPos(-4, -1, -5));
        spinor.add(new BlockPos(-4, -1, -4));
        spinor.add(new BlockPos(-4, -1, -1));
        spinor.add(new BlockPos(-4, 1, -5));
        spinor.add(new BlockPos(-4, 1, -4));
        spinor.add(new BlockPos(-4, 1, -1));
        spinor.add(new BlockPos(-4, 2, -3));
        spinor.add(new BlockPos(-4, 2, -2));
        spinor.add(new BlockPos(-3, -3, -3));
        spinor.add(new BlockPos(-3, -2, -4));
        spinor.add(new BlockPos(-3, -2, -2));
        spinor.add(new BlockPos(-3, -1, -5));
        spinor.add(new BlockPos(-3, -1, -1));
        spinor.add(new BlockPos(-3, 1, -5));
        spinor.add(new BlockPos(-3, 1, -1));
        spinor.add(new BlockPos(-3, 2, -4));
        spinor.add(new BlockPos(-3, 2, -2));
        spinor.add(new BlockPos(-3, 3, -3));
        spinor.add(new BlockPos(-2, -9, 0));
        spinor.add(new BlockPos(-2, -8, 0));
        spinor.add(new BlockPos(-2, -7, -1));
        spinor.add(new BlockPos(-2, -6, -2));
        spinor.add(new BlockPos(-2, -6, -1));
        spinor.add(new BlockPos(-2, -5, -3));
        spinor.add(new BlockPos(-2, -5, -2));
        spinor.add(new BlockPos(-2, -4, -3));
        spinor.add(new BlockPos(-2, -4, -2));
        spinor.add(new BlockPos(-2, -3, -4));
        spinor.add(new BlockPos(-2, -3, -2));
        spinor.add(new BlockPos(-2, -2, -4));
        spinor.add(new BlockPos(-2, -2, -2));
        spinor.add(new BlockPos(-2, -1, -5));
        spinor.add(new BlockPos(-2, -1, -1));
        spinor.add(new BlockPos(-2, 1, -5));
        spinor.add(new BlockPos(-2, 1, -1));
        spinor.add(new BlockPos(-2, 2, -4));
        spinor.add(new BlockPos(-2, 2, -2));
        spinor.add(new BlockPos(-2, 3, -4));
        spinor.add(new BlockPos(-2, 3, -2));
        spinor.add(new BlockPos(-2, 4, -3));
        spinor.add(new BlockPos(-2, 4, -2));
        spinor.add(new BlockPos(-2, 5, -3));
        spinor.add(new BlockPos(-2, 5, -2));
        spinor.add(new BlockPos(-2, 6, -2));
        spinor.add(new BlockPos(-2, 6, -1));
        spinor.add(new BlockPos(-2, 7, -1));
        spinor.add(new BlockPos(-2, 8, 0));
        spinor.add(new BlockPos(-2, 9, 0));
        spinor.add(new BlockPos(-1, -11, 2));
        spinor.add(new BlockPos(-1, -11, 3));
        spinor.add(new BlockPos(-1, -11, 4));
        spinor.add(new BlockPos(-1, -11, 5));
        spinor.add(new BlockPos(-1, -10, 0));
        spinor.add(new BlockPos(-1, -10, 1));
        spinor.add(new BlockPos(-1, -10, 2));
        spinor.add(new BlockPos(-1, -10, 3));
        spinor.add(new BlockPos(-1, -9, -1));
        spinor.add(new BlockPos(-1, -9, 1));
        spinor.add(new BlockPos(-1, -9, 2));
        spinor.add(new BlockPos(-1, -8, -2));
        spinor.add(new BlockPos(-1, -8, -1));
        spinor.add(new BlockPos(-1, -8, 1));
        spinor.add(new BlockPos(-1, -7, -3));
        spinor.add(new BlockPos(-1, -7, -2));
        spinor.add(new BlockPos(-1, -7, 0));
        spinor.add(new BlockPos(-1, -7, 1));
        spinor.add(new BlockPos(-1, -6, -4));
        spinor.add(new BlockPos(-1, -6, -3));
        spinor.add(new BlockPos(-1, -6, 0));
        spinor.add(new BlockPos(-1, -5, -4));
        spinor.add(new BlockPos(-1, -5, -1));
        spinor.add(new BlockPos(-1, -5, 0));
        spinor.add(new BlockPos(-1, -4, -5));
        spinor.add(new BlockPos(-1, -4, -4));
        spinor.add(new BlockPos(-1, -4, -1));
        spinor.add(new BlockPos(-1, -3, -5));
        spinor.add(new BlockPos(-1, -3, -1));
        spinor.add(new BlockPos(-1, -2, -5));
        spinor.add(new BlockPos(-1, -2, -1));
        spinor.add(new BlockPos(-1, -1, -5));
        spinor.add(new BlockPos(-1, -1, -1));
        spinor.add(new BlockPos(-1, 1, -5));
        spinor.add(new BlockPos(-1, 1, -1));
        spinor.add(new BlockPos(-1, 2, -5));
        spinor.add(new BlockPos(-1, 2, -1));
        spinor.add(new BlockPos(-1, 3, -5));
        spinor.add(new BlockPos(-1, 3, -1));
        spinor.add(new BlockPos(-1, 4, -5));
        spinor.add(new BlockPos(-1, 4, -4));
        spinor.add(new BlockPos(-1, 4, -1));
        spinor.add(new BlockPos(-1, 5, -4));
        spinor.add(new BlockPos(-1, 5, -1));
        spinor.add(new BlockPos(-1, 5, 0));
        spinor.add(new BlockPos(-1, 6, -4));
        spinor.add(new BlockPos(-1, 6, -3));
        spinor.add(new BlockPos(-1, 6, 0));
        spinor.add(new BlockPos(-1, 7, -3));
        spinor.add(new BlockPos(-1, 7, -2));
        spinor.add(new BlockPos(-1, 7, 0));
        spinor.add(new BlockPos(-1, 7, 1));
        spinor.add(new BlockPos(-1, 8, -2));
        spinor.add(new BlockPos(-1, 8, -1));
        spinor.add(new BlockPos(-1, 8, 1));
        spinor.add(new BlockPos(-1, 9, -1));
        spinor.add(new BlockPos(-1, 9, 1));
        spinor.add(new BlockPos(-1, 9, 2));
        spinor.add(new BlockPos(-1, 10, 0));
        spinor.add(new BlockPos(-1, 10, 1));
        spinor.add(new BlockPos(-1, 10, 2));
        spinor.add(new BlockPos(-1, 10, 3));
        spinor.add(new BlockPos(-1, 11, 2));
        spinor.add(new BlockPos(-1, 11, 3));
        spinor.add(new BlockPos(-1, 11, 4));
        spinor.add(new BlockPos(-1, 11, 5));
        spinor.add(new BlockPos(1, -11, 2));
        spinor.add(new BlockPos(1, -11, 3));
        spinor.add(new BlockPos(1, -11, 4));
        spinor.add(new BlockPos(1, -11, 5));
        spinor.add(new BlockPos(1, -10, 0));
        spinor.add(new BlockPos(1, -10, 1));
        spinor.add(new BlockPos(1, -10, 2));
        spinor.add(new BlockPos(1, -10, 3));
        spinor.add(new BlockPos(1, -9, -1));
        spinor.add(new BlockPos(1, -9, 0));
        spinor.add(new BlockPos(1, -9, 1));
        spinor.add(new BlockPos(1, -9, 2));
        spinor.add(new BlockPos(1, -8, -2));
        spinor.add(new BlockPos(1, -8, -1));
        spinor.add(new BlockPos(1, -8, 1));
        spinor.add(new BlockPos(1, -7, -3));
        spinor.add(new BlockPos(1, -7, -2));
        spinor.add(new BlockPos(1, -7, 0));
        spinor.add(new BlockPos(1, -7, 1));
        spinor.add(new BlockPos(1, -6, -4));
        spinor.add(new BlockPos(1, -6, -3));
        spinor.add(new BlockPos(1, -6, 0));
        spinor.add(new BlockPos(1, -5, -4));
        spinor.add(new BlockPos(1, -5, -1));
        spinor.add(new BlockPos(1, -5, 0));
        spinor.add(new BlockPos(1, -4, -5));
        spinor.add(new BlockPos(1, -4, -4));
        spinor.add(new BlockPos(1, -4, -1));
        spinor.add(new BlockPos(1, -3, -5));
        spinor.add(new BlockPos(1, -3, -1));
        spinor.add(new BlockPos(1, -2, -5));
        spinor.add(new BlockPos(1, -2, -1));
        spinor.add(new BlockPos(1, -1, -5));
        spinor.add(new BlockPos(1, -1, -1));
        spinor.add(new BlockPos(1, 1, -5));
        spinor.add(new BlockPos(1, 1, -1));
        spinor.add(new BlockPos(1, 2, -5));
        spinor.add(new BlockPos(1, 2, -1));
        spinor.add(new BlockPos(1, 3, -5));
        spinor.add(new BlockPos(1, 3, -1));
        spinor.add(new BlockPos(1, 4, -5));
        spinor.add(new BlockPos(1, 4, -4));
        spinor.add(new BlockPos(1, 4, -1));
        spinor.add(new BlockPos(1, 5, -4));
        spinor.add(new BlockPos(1, 5, -1));
        spinor.add(new BlockPos(1, 5, 0));
        spinor.add(new BlockPos(1, 6, -4));
        spinor.add(new BlockPos(1, 6, -3));
        spinor.add(new BlockPos(1, 6, 0));
        spinor.add(new BlockPos(1, 7, -3));
        spinor.add(new BlockPos(1, 7, -2));
        spinor.add(new BlockPos(1, 7, 0));
        spinor.add(new BlockPos(1, 7, 1));
        spinor.add(new BlockPos(1, 8, -2));
        spinor.add(new BlockPos(1, 8, -1));
        spinor.add(new BlockPos(1, 8, 1));
        spinor.add(new BlockPos(1, 9, -1));
        spinor.add(new BlockPos(1, 9, 0));
        spinor.add(new BlockPos(1, 9, 1));
        spinor.add(new BlockPos(1, 9, 2));
        spinor.add(new BlockPos(1, 10, 0));
        spinor.add(new BlockPos(1, 10, 1));
        spinor.add(new BlockPos(1, 10, 2));
        spinor.add(new BlockPos(1, 10, 3));
        spinor.add(new BlockPos(1, 11, 2));
        spinor.add(new BlockPos(1, 11, 3));
        spinor.add(new BlockPos(1, 11, 4));
        spinor.add(new BlockPos(1, 11, 5));
        spinor.add(new BlockPos(2, -9, 0));
        spinor.add(new BlockPos(2, -8, 0));
        spinor.add(new BlockPos(2, -7, -1));
        spinor.add(new BlockPos(2, -6, -2));
        spinor.add(new BlockPos(2, -6, -1));
        spinor.add(new BlockPos(2, -5, -3));
        spinor.add(new BlockPos(2, -5, -2));
        spinor.add(new BlockPos(2, -4, -3));
        spinor.add(new BlockPos(2, -4, -2));
        spinor.add(new BlockPos(2, -3, -4));
        spinor.add(new BlockPos(2, -3, -3));
        spinor.add(new BlockPos(2, -3, -2));
        spinor.add(new BlockPos(2, -2, -4));
        spinor.add(new BlockPos(2, -2, -2));
        spinor.add(new BlockPos(2, -1, -5));
        spinor.add(new BlockPos(2, -1, -1));
        spinor.add(new BlockPos(2, 1, -5));
        spinor.add(new BlockPos(2, 1, -1));
        spinor.add(new BlockPos(2, 2, -4));
        spinor.add(new BlockPos(2, 2, -2));
        spinor.add(new BlockPos(2, 3, -4));
        spinor.add(new BlockPos(2, 3, -3));
        spinor.add(new BlockPos(2, 3, -2));
        spinor.add(new BlockPos(2, 4, -3));
        spinor.add(new BlockPos(2, 4, -2));
        spinor.add(new BlockPos(2, 5, -3));
        spinor.add(new BlockPos(2, 5, -2));
        spinor.add(new BlockPos(2, 6, -2));
        spinor.add(new BlockPos(2, 6, -1));
        spinor.add(new BlockPos(2, 7, -1));
        spinor.add(new BlockPos(2, 8, 0));
        spinor.add(new BlockPos(2, 9, 0));
        spinor.add(new BlockPos(3, -3, -3));
        spinor.add(new BlockPos(3, -2, -4));
        spinor.add(new BlockPos(3, -2, -3));
        spinor.add(new BlockPos(3, -2, -2));
        spinor.add(new BlockPos(3, -1, -5));
        spinor.add(new BlockPos(3, -1, -1));
        spinor.add(new BlockPos(3, 1, -5));
        spinor.add(new BlockPos(3, 1, -1));
        spinor.add(new BlockPos(3, 2, -4));
        spinor.add(new BlockPos(3, 2, -3));
        spinor.add(new BlockPos(3, 2, -2));
        spinor.add(new BlockPos(3, 3, -3));
        spinor.add(new BlockPos(4, -2, -3));
        spinor.add(new BlockPos(4, -2, -2));
        spinor.add(new BlockPos(4, -1, -5));
        spinor.add(new BlockPos(4, -1, -4));
        spinor.add(new BlockPos(4, -1, -1));
        spinor.add(new BlockPos(4, 1, -5));
        spinor.add(new BlockPos(4, 1, -4));
        spinor.add(new BlockPos(4, 1, -1));
        spinor.add(new BlockPos(4, 2, -3));
        spinor.add(new BlockPos(4, 2, -2));
        spinor.add(new BlockPos(5, -2, -3));
        spinor.add(new BlockPos(5, -2, -2));
        spinor.add(new BlockPos(5, -1, -4));
        spinor.add(new BlockPos(5, -1, -1));
        spinor.add(new BlockPos(5, -1, 0));
        spinor.add(new BlockPos(5, 1, -4));
        spinor.add(new BlockPos(5, 1, -1));
        spinor.add(new BlockPos(5, 1, 0));
        spinor.add(new BlockPos(5, 2, -3));
        spinor.add(new BlockPos(5, 2, -2));
        spinor.add(new BlockPos(6, -2, -2));
        spinor.add(new BlockPos(6, -2, -1));
        spinor.add(new BlockPos(6, -1, -4));
        spinor.add(new BlockPos(6, -1, -3));
        spinor.add(new BlockPos(6, -1, 0));
        spinor.add(new BlockPos(6, 1, -4));
        spinor.add(new BlockPos(6, 1, -3));
        spinor.add(new BlockPos(6, 1, 0));
        spinor.add(new BlockPos(6, 2, -2));
        spinor.add(new BlockPos(6, 2, -1));
        spinor.add(new BlockPos(7, -2, -1));
        spinor.add(new BlockPos(7, -1, -3));
        spinor.add(new BlockPos(7, -1, -2));
        spinor.add(new BlockPos(7, -1, 0));
        spinor.add(new BlockPos(7, -1, 1));
        spinor.add(new BlockPos(7, 1, -3));
        spinor.add(new BlockPos(7, 1, -2));
        spinor.add(new BlockPos(7, 1, 0));
        spinor.add(new BlockPos(7, 1, 1));
        spinor.add(new BlockPos(7, 2, -1));
        spinor.add(new BlockPos(8, -2, 0));
        spinor.add(new BlockPos(8, -1, -2));
        spinor.add(new BlockPos(8, -1, -1));
        spinor.add(new BlockPos(8, -1, 1));
        spinor.add(new BlockPos(8, 1, -2));
        spinor.add(new BlockPos(8, 1, -1));
        spinor.add(new BlockPos(8, 1, 1));
        spinor.add(new BlockPos(8, 2, 0));
        spinor.add(new BlockPos(9, -2, 0));
        spinor.add(new BlockPos(9, -1, -1));
        spinor.add(new BlockPos(9, -1, 0));
        spinor.add(new BlockPos(9, -1, 1));
        spinor.add(new BlockPos(9, -1, 2));
        spinor.add(new BlockPos(9, 1, -1));
        spinor.add(new BlockPos(9, 1, 0));
        spinor.add(new BlockPos(9, 1, 1));
        spinor.add(new BlockPos(9, 1, 2));
        spinor.add(new BlockPos(9, 2, 0));
        spinor.add(new BlockPos(10, -1, 0));
        spinor.add(new BlockPos(10, -1, 1));
        spinor.add(new BlockPos(10, -1, 2));
        spinor.add(new BlockPos(10, -1, 3));
        spinor.add(new BlockPos(10, 1, 0));
        spinor.add(new BlockPos(10, 1, 1));
        spinor.add(new BlockPos(10, 1, 2));
        spinor.add(new BlockPos(10, 1, 3));
        spinor.add(new BlockPos(11, -1, 2));
        spinor.add(new BlockPos(11, -1, 3));
        spinor.add(new BlockPos(11, -1, 4));
        spinor.add(new BlockPos(11, -1, 5));
        spinor.add(new BlockPos(11, 1, 2));
        spinor.add(new BlockPos(11, 1, 3));
        spinor.add(new BlockPos(11, 1, 4));
        spinor.add(new BlockPos(11, 1, 5));
        SPINOR_CASING_SET = Collections.unmodifiableSet(spinor);

        Set<BlockPos> all = new HashSet<>();
        all.addAll(TENSOR_CASING_SET);
        all.addAll(CAUSAL_ANCHOR_SET);
        all.addAll(SPINOR_CASING_SET);
        ALL_STRUCTURE_SET = Collections.unmodifiableSet(all);
    }

    public static EnumFacing getControllerFacing(World world, BlockPos controllerPos) {
        net.minecraft.block.state.IBlockState state = world.getBlockState(controllerPos);
        if (state.getBlock() instanceof com.github.aeddddd.ae2enhanced.block.BlockComputationCore) {
            return state.getValue(com.github.aeddddd.ae2enhanced.block.BlockComputationCore.FACING);
        }
        return EnumFacing.NORTH;
    }

    public static BlockPos rotate(BlockPos rel, EnumFacing facing) {
        if (facing == EnumFacing.NORTH) return rel;
        int x = rel.getX();
        int y = rel.getY();
        int z = rel.getZ();
        switch (facing) {
            case SOUTH: return new BlockPos(-x, y, -z);
            case EAST:  return new BlockPos(-z, y, x);
            case WEST:  return new BlockPos(z, y, -x);
            default:    return rel;
        }
    }

    /**
     * ��֤�ṹ�����ԡ�
     * @return ��֤����������Ƿ�ͨ����ȱʧ����ͳ�ơ����ê������������������Ĳ�������
     */
    public static ValidationResult validate(World world, BlockPos controllerPos) {
        EnumFacing facing = getControllerFacing(world, controllerPos);
        Map<Block, Integer> missing = new LinkedHashMap<>();
        int causalCount = 0;

        // ��֤�㶨���������
        for (BlockPos rel : TENSOR_CASING_SET) {
            BlockPos actual = controllerPos.add(rotate(rel, facing));
            if (!world.isBlockLoaded(actual)) continue;
            if (world.getBlockState(actual).getBlock() != ModBlocks.CONSTANT_TENSOR_FIELD_CASING) {
                if (actual.equals(controllerPos)) continue; // ������λ������ block1 ռ��
                missing.put(ModBlocks.CONSTANT_TENSOR_FIELD_CASING, missing.getOrDefault(ModBlocks.CONSTANT_TENSOR_FIELD_CASING, 0) + 1);
            }
        }

        // ��֤���ê������
        for (BlockPos rel : CAUSAL_ANCHOR_SET) {
            BlockPos actual = controllerPos.add(rotate(rel, facing));
            if (!world.isBlockLoaded(actual)) continue;
            if (world.getBlockState(actual).getBlock() == ModBlocks.CAUSAL_ANCHOR_CORE) {
                causalCount++;
            } else {
                missing.put(ModBlocks.CAUSAL_ANCHOR_CORE, missing.getOrDefault(ModBlocks.CAUSAL_ANCHOR_CORE, 0) + 1);
            }
        }

        // ��֤�㶨���������
        for (BlockPos rel : SPINOR_CASING_SET) {
            BlockPos actual = controllerPos.add(rotate(rel, facing));
            if (!world.isBlockLoaded(actual)) continue;
            if (world.getBlockState(actual).getBlock() != ModBlocks.CONSTANT_SPINOR_FIELD_CASING) {
                missing.put(ModBlocks.CONSTANT_SPINOR_FIELD_CASING, missing.getOrDefault(ModBlocks.CONSTANT_SPINOR_FIELD_CASING, 0) + 1);
            }
        }

        // ��֤ ME �ӿ�
        BlockPos meInterfacePos = controllerPos.add(rotate(ME_INTERFACE_REL, facing));
        boolean meInterfaceValid = false;
        if (world.isBlockLoaded(meInterfacePos)) {
            meInterfaceValid = world.getBlockState(meInterfacePos).getBlock() == ModBlocks.SUPER_CRAFTING_INTERFACE;
        }
        if (!meInterfaceValid) {
            missing.put(ModBlocks.SUPER_CRAFTING_INTERFACE, missing.getOrDefault(ModBlocks.SUPER_CRAFTING_INTERFACE, 0) + 1);
        }

        boolean passed = missing.isEmpty();
        int parallel = passed ? computeParallel(causalCount) : 0;

        return new ValidationResult(passed, missing, causalCount, parallel);
    }

    /**
     * �������ê�������������㲢�����ޡ�
     * ��ʽ��1024 + floor(causalCount / 21) * 1024������ 16384
     */
    public static int computeParallel(int causalCount) {
        int base = AE2EnhancedConfig.crafting.baseParallel;
        int step = AE2EnhancedConfig.crafting.parallelPerAnchorCount;
        int max = AE2EnhancedConfig.crafting.maxParallel;
        int extra = (causalCount / step) * 1024;
        return Math.min(max, base + extra);
    }

    public static class ValidationResult {
        public final boolean passed;
        public final Map<Block, Integer> missing;
        public final int causalAnchorCount;
        public final int parallelLimit;

        public ValidationResult(boolean passed, Map<Block, Integer> missing, int causalAnchorCount, int parallelLimit) {
            this.passed = passed;
            this.missing = Collections.unmodifiableMap(missing);
            this.causalAnchorCount = causalAnchorCount;
            this.parallelLimit = parallelLimit;
        }
    }
}
