modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="ae2enhanced"
version="${version}"
displayName="AE2Enhanced"
description='''Supercausal Assembly Hub for Applied Energistics 2'''
authors="aeddddd"

[[dependencies.ae2enhanced]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ae2enhanced]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ae2enhanced]]
    modId="ae2"
    type="required"
    versionRange="[19.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[mixins]]
config="ae2enhanced.mixins.json"
